name = "portfolio-auth"
main = "worker.js"
compatibility_date = "2026-01-01"

[env.production]
  route = "jonathanreyesmorel.com/"
  zone_id = "<YOUR_ZONE_ID>"

[vars]
  AUTH_CODE = "3212"
  SESSION_SECRET = "Crimson-falcon-dances-under-silent-moons-while-emerald-rivers-whisper-secrets"
