name = "night"
main = "worker.js"
compatibility_date = "2026-01-01"

[env.production]
  route = "jonathanreyesmorel.com/*"
  vars = { AUTH_CODE = "0309", SESSION_SECRET = "Crimson-falcon-dances-under-silent-moons-while-emerald-rivers-whisper-secrets", GIT_HASH = "fd730ad", GIT_MESSAGE = "update", GIT_TIMESTAMP = "2026-03-22T10:23:01-04:00", GITHUB_REPO = "jmorel03/portfolio" }
